Print filepath in fromAbsoluteFilePath error
haskell/hackage-security pull request #261
Opened 2022-01-29 02:37 UTC by newhoggy

I'm getting this error in `cabal` and have no idea what the directory is that is causing this problem.

https://github.com/input-output-hk/cardano-node/runs/4988750629?check_suite_focus=true

Printing the filepath that is causing the error will help making these kinds of issues easier to diagnose.

2022-01-29 08:21 UTC, Mikolaj requested changes
LGTM except for the compatibility issue (I think we still support GHCs >= 8)

2022-01-29 11:40 UTC, hasufell commented on hackage-security/src/Hackage/Security/Util/Path.hs
> +  | otherwise               = error ("fromAbsoluteFilePath: not an absolute path: " <> fp)
```suggestion
  | otherwise               = error ("fromAbsoluteFilePath: not an absolute path: " ++ fp)
```

2022-01-31 11:36 UTC, Mikolaj commented
@newhoggy: I think once you include what @hasufell suggested, it should compile on old GHCs and we can merge.

2022-02-01 08:09 UTC, Mikolaj commented
I think @newhoggy is busy, so let' me try to merge the fix myself...

2022-02-01 09:11 UTC, Mikolaj approved these changes
LGTM

2022-02-01 09:11 UTC, merged

2022-02-01 09:11 UTC, Mikolaj commented
Thank you!